const countyData = [
  { id: 1, name: "基隆市", value: "KLU" },
  { id: 2, name: "新北市", value: "TPH" },
  { id: 3, name: "臺北市", value: "TPE" },
  { id: 4, name: "桃園市", value: "TYC" },
  { id: 5, name: "新竹縣", value: "HSH" },
  { id: 6, name: "新竹市", value: "HSC" },
  { id: 7, name: "苗栗市", value: "MAC" },
  { id: 8, name: "苗栗縣", value: "MAL" },
  { id: 9, name: "臺中市", value: "TXG" },
  { id: 10, name: "彰化縣", value: "CWH" },
  { id: 11, name: "彰化市", value: "CWS" },
  { id: 12, name: "南投市", value: "NTC" },
  { id: 13, name: "南投縣", value: "NTO" },
  { id: 14, name: "雲林縣", value: "YLH" },
  { id: 15, name: "嘉義縣", value: "CHY" },
  { id: 16, name: "嘉義市", value: "CYI" },
  { id: 17, name: "臺南市", value: "TNN" },
  { id: 18, name: "高雄市", value: "KHH" },
  { id: 19, name: "屏東縣", value: "IUH" },
  { id: 20, name: "屏東市", value: "PTS" },
  { id: 21, name: "宜蘭縣", value: "ILN" },
  { id: 22, name: "宜蘭市", value: "ILC" },
  { id: 23, name: "花蓮縣", value: "HWA" },
  { id: 24, name: "花蓮市", value: "HWC" },
  { id: 25, name: "臺東市", value: "TTC" },
  { id: 26, name: "臺東縣", value: "TTT" },
  { id: 27, name: "澎湖縣", value: "PEH" },
  { id: 28, name: "金門縣", value: "KMN" },
  { id: 29, name: "連江縣", value: "LNN" },
];

export default countyData;
